version: '3.8'

networks:
  wordle-network:
    driver: bridge

volumes:
  pg_wordle:

services:
  wordle_db:
    image: postgres:16.0
    container_name: wordle_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wordle_db
    ports:
      - '5434:5432'
    volumes:
      - pg_wordle:/var/lib/postgresql/data
    networks:
      - wordle-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - wordle-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - wordle-network

  game-service:
    build:
      context: ./backend
      dockerfile: ./game-service/Dockerfile
    container_name: game-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081
    depends_on:
      - wordle_db
      - kafka
    networks:
      - wordle-network

  user-service:
    build:
      context: ./backend
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8082
    depends_on:
      - wordle_db
      - kafka
    networks:
      - wordle-network

  api-gateway:
    build:
      context: ./backend
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - user-service
      - game-service
    networks:
      - wordle-network
    extra_hosts:
      - "host.docker.internal:host-gateway"